export const fresh = () => ({
  theme: "light",
  dock: null,
  durations: { focus: 50, break: 10, long: 20 },
  auto: false,
  subject: "",
  subjects: [],
  subjectColors: {},
  archivedSubjects: [],
  tasks: [],
  sessions: [],
  round: 0,
  mode: "focus",
  clockView: false,
  timer: {
    running: false,
    remaining: 3000,
    endAt: null,
    startedAt: null,
    credited: 0,
  },
  anki: null,
  ankiGoal: 25,
  prayers: [],
  prayerChecks: {},
  prayerTimer: null,
  prayerTimes: {},
  prayerLocation: "",
  prayerDate: "",
  method: "2",
  view: "week",
  longEvery: 0,
  sound: true,
  soundVolume: 0.22,
  prayerPeek: false,
  widgetPositions: {},
  prayerSource: null,
  statsView: "all",
  taskFilter: "active",
  prayerView: false,
  prayerDuration: 10,
});
